global_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.2
  width: 20
  height: 20
  rolling_window: true
  resolution: 0.05

