local_costmap:
  global_frame: odom
  robot_base_frame: chassis

  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.2

  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05

