local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.2

  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05

