obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[ 0.3,  0.3], [-0.3,  0.3], [-0.3, -0.3], [ 0.3, -0.3]]
footprint_padding: 0.03
global_frame: odom
robot_base_frame: chassis

update_frequency: 1.0
publish_frequency: 1.0
transform_tolerance: 0.2

rolling_window: true
width: 10
height: 10
resolution: 0.05

plugins:
  - {name: sonar,             type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation,         type: "costmap_2d::InflationLayer"}

inflation:
  inflation_radius: 0.4

sonar:
  frame: sonar_front
  topics: ["/sensor/sonar/front"]
  no_readings_timeout: 2.0
  clear_on_max_reading: true