disp12MaxDiff: 0
fullDP: false
P1: 200.0
P2: 400.0
correlation_window_size: 5
disparity_range: 64
min_disparity: 0
prefilter_cap: 31
prefilter_size: 17
speckle_range: 22
speckle_size: 901
stereo_algorithm: 1
texture_threshold: 958
uniqueness_ratio: 18.0
